export interface Category {
  id: string;
  name: string;
  emoji: string;
  words: WordEntry[];
}

export interface WordEntry {
  word: string;
  hint: string;
  difficulty: "easy" | "medium" | "hard";
}

export const CATEGORIES: Category[] = [
  {
    id: "food",
    name: "Food & Drinks",
    emoji: "🍕",
    words: [
      { word: "PIZZA", hint: "Cheesy Italian disc", difficulty: "easy" },
      { word: "SUSHI", hint: "Japanese rice & fish art", difficulty: "easy" },
      { word: "TACOS", hint: "Folded Mexican street food", difficulty: "easy" },
      { word: "PASTA", hint: "Italian noodle dish", difficulty: "easy" },
      { word: "CURRY", hint: "Spiced South Asian stew", difficulty: "easy" },
      { word: "RAMEN", hint: "Japanese noodle soup", difficulty: "easy" },
      { word: "WAFFLES", hint: "Grid-patterned breakfast", difficulty: "easy" },
      { word: "PANCAKES", hint: "Flat breakfast stacks with syrup", difficulty: "easy" },
      { word: "CHOCOLATE", hint: "Sweet cocoa treat", difficulty: "medium" },
      { word: "AVOCADO", hint: "Green toast topping", difficulty: "medium" },
      { word: "ESPRESSO", hint: "Strong Italian coffee shot", difficulty: "medium" },
      { word: "BROWNIE", hint: "Fudgy chocolate square", difficulty: "easy" },
      { word: "BURRITO", hint: "Rolled Mexican wrap", difficulty: "medium" },
      { word: "DUMPLINGS", hint: "Stuffed dough pockets", difficulty: "medium" },
      { word: "NACHOS", hint: "Chips with melted cheese", difficulty: "easy" },
      { word: "PRETZEL", hint: "Twisted salty bread", difficulty: "medium" },
      { word: "CHEESECAKE", hint: "Creamy baked dessert", difficulty: "medium" },
      { word: "MACARONS", hint: "Colorful French sandwich cookies", difficulty: "hard" },
      { word: "FONDUE", hint: "Swiss melted cheese dip", difficulty: "medium" },
      { word: "GNOCCHI", hint: "Italian potato dumplings", difficulty: "hard" },
      { word: "RISOTTO", hint: "Creamy Italian rice dish", difficulty: "medium" },
      { word: "CROISSANT", hint: "Flaky French crescent pastry", difficulty: "hard" },
      { word: "TIRAMISU", hint: "Coffee-soaked Italian dessert", difficulty: "hard" },
      { word: "SMOOTHIE", hint: "Blended fruit drink", difficulty: "easy" },
      { word: "LASAGNE", hint: "Layered Italian pasta bake", difficulty: "medium" },
      { word: "BRUSCHETTA", hint: "Toasted Italian bread with toppings", difficulty: "hard" },
      { word: "QUESADILLA", hint: "Toasted cheese-filled tortilla", difficulty: "hard" },
      { word: "PHO", hint: "Vietnamese noodle broth", difficulty: "easy" },
      { word: "BAKLAVA", hint: "Honey-soaked layered pastry", difficulty: "hard" },
      { word: "CAPPUCCINO", hint: "Frothy espresso coffee", difficulty: "medium" },
      { word: "DOUGHNUT", hint: "Ring-shaped fried dough", difficulty: "medium" },
      { word: "LEMONADE", hint: "Chilled citrus summer drink", difficulty: "easy" },
      { word: "GUACAMOLE", hint: "Mashed avocado dip", difficulty: "hard" },
      { word: "CINNAMON", hint: "Warm spice for baking", difficulty: "medium" },
      { word: "MEATBALLS", hint: "Italian pasta companions", difficulty: "medium" },
    ],
  },
  {
    id: "travel",
    name: "Travel & Places",
    emoji: "✈️",
    words: [
      { word: "PARIS", hint: "City of light and love", difficulty: "easy" },
      { word: "TOKYO", hint: "Japan's neon capital", difficulty: "easy" },
      { word: "BALI", hint: "Indonesian island paradise", difficulty: "easy" },
      { word: "SANTORINI", hint: "Greek island with white buildings", difficulty: "medium" },
      { word: "LONDON", hint: "City with Big Ben", difficulty: "easy" },
      { word: "MALDIVES", hint: "Overwater bungalow destination", difficulty: "medium" },
      { word: "AMSTERDAM", hint: "City of canals and bikes", difficulty: "medium" },
      { word: "VENICE", hint: "Italian city on water", difficulty: "easy" },
      { word: "BARCELONA", hint: "City of Gaudi and tapas", difficulty: "medium" },
      { word: "SAFARI", hint: "African wildlife adventure", difficulty: "easy" },
      { word: "CRUISE", hint: "Floating hotel vacation", difficulty: "easy" },
      { word: "BACKPACKING", hint: "Budget travel with a big pack", difficulty: "hard" },
      { word: "WATERFALL", hint: "Cascading natural water feature", difficulty: "medium" },
      { word: "LIGHTHOUSE", hint: "Coastal tower guiding ships", difficulty: "medium" },
      { word: "PASSPORT", hint: "International travel document", difficulty: "medium" },
      { word: "SOUVENIR", hint: "Memento from a trip", difficulty: "hard" },
      { word: "ROADTRIP", hint: "Long journey by car", difficulty: "medium" },
      { word: "ADVENTURE", hint: "Exciting risky experience", difficulty: "medium" },
      { word: "ISTANBUL", hint: "City bridging Europe and Asia", difficulty: "medium" },
      { word: "CAPPADOCIA", hint: "Turkish hot-air balloon region", difficulty: "hard" },
      { word: "MARRAKECH", hint: "Moroccan city of souks", difficulty: "hard" },
      { word: "KYOTO", hint: "Japan's ancient temple city", difficulty: "easy" },
      { word: "DUBROVNIK", hint: "Game of Thrones Croatian coast", difficulty: "hard" },
      { word: "PATAGONIA", hint: "Wild southern South America", difficulty: "hard" },
      { word: "FJORD", hint: "Norwegian coastal inlet", difficulty: "easy" },
      { word: "GLACIER", hint: "Slow-moving river of ice", difficulty: "medium" },
      { word: "ARCHIPELAGO", hint: "Chain of islands", difficulty: "hard" },
      { word: "ITINERARY", hint: "Travel schedule document", difficulty: "hard" },
      { word: "HOSTEL", hint: "Budget traveler accommodation", difficulty: "medium" },
      { word: "LAYOVER", hint: "Airport waiting time between flights", difficulty: "medium" },
    ],
  },
  {
    id: "romance",
    name: "Love & Romance",
    emoji: "💕",
    words: [
      { word: "KISS", hint: "Lips touch lips", difficulty: "easy" },
      { word: "HUG", hint: "Warm arm embrace", difficulty: "easy" },
      { word: "FLOWERS", hint: "Classic romantic gift", difficulty: "easy" },
      { word: "SOULMATE", hint: "Perfect romantic partner", difficulty: "medium" },
      { word: "BUTTERFLIES", hint: "That nervous feeling in your stomach", difficulty: "hard" },
      { word: "MOONLIGHT", hint: "Romantic night glow", difficulty: "medium" },
      { word: "PICNIC", hint: "Outdoor meal on a blanket", difficulty: "easy" },
      { word: "ANNIVERSARY", hint: "Yearly relationship milestone", difficulty: "hard" },
      { word: "SWEETHEART", hint: "Term of endearment", difficulty: "medium" },
      { word: "DEVOTION", hint: "Deep dedicated love", difficulty: "medium" },
      { word: "CHERISH", hint: "To hold dear", difficulty: "medium" },
      { word: "AFFECTION", hint: "Warm tender feelings", difficulty: "medium" },
      { word: "PROPOSAL", hint: "Will you marry me moment", difficulty: "medium" },
      { word: "CANDLELIGHT", hint: "Romantic dinner ambiance", difficulty: "hard" },
      { word: "HEARTBEAT", hint: "Rhythm that quickens for love", difficulty: "medium" },
      { word: "ENCHANTED", hint: "Under a magical spell", difficulty: "medium" },
      { word: "SERENADE", hint: "Musical love performance", difficulty: "medium" },
      { word: "HONEYMOON", hint: "First vacation as newlyweds", difficulty: "medium" },
      { word: "INFATUATION", hint: "Intense short-lived passion", difficulty: "hard" },
      { word: "ADORATION", hint: "Deep admiring love", difficulty: "medium" },
      { word: "PROMISE", hint: "Commitment to keep a vow", difficulty: "easy" },
      { word: "INTIMACY", hint: "Deep close connection", difficulty: "medium" },
      { word: "BLUSHING", hint: "Red face from love", difficulty: "medium" },
      { word: "STARGAZING", hint: "Looking up at night sky together", difficulty: "medium" },
      { word: "ELOPEMENT", hint: "Running away to get married", difficulty: "hard" },
      { word: "COURTSHIP", hint: "Dating before marriage", difficulty: "hard" },
      { word: "TENDERNESS", hint: "Gentle loving care", difficulty: "hard" },
      { word: "SMITTEN", hint: "Completely taken by someone", difficulty: "medium" },
      { word: "YEARNING", hint: "Deep longing feeling", difficulty: "medium" },
      { word: "FONDNESS", hint: "Warm liking for someone", difficulty: "medium" },
    ],
  },
  {
    id: "movies",
    name: "Movies & Shows",
    emoji: "🎬",
    words: [
      { word: "TITANIC", hint: "Ship disaster love story", difficulty: "easy" },
      { word: "INCEPTION", hint: "Dream within a dream", difficulty: "medium" },
      { word: "FROZEN", hint: "Let it go sister magic", difficulty: "easy" },
      { word: "BATMAN", hint: "Dark knight of Gotham", difficulty: "easy" },
      { word: "MATRIX", hint: "Red pill or blue pill", difficulty: "medium" },
      { word: "GLADIATOR", hint: "Are you not entertained?", difficulty: "medium" },
      { word: "INTERSTELLAR", hint: "Wormhole space odyssey", difficulty: "hard" },
      { word: "PARASITE", hint: "Korean Oscar-winning thriller", difficulty: "medium" },
      { word: "CASABLANCA", hint: "Classic wartime love story", difficulty: "hard" },
      { word: "BRAVEHEART", hint: "Scottish freedom warrior", difficulty: "medium" },
      { word: "SPIRITAWAY", hint: "Japanese animated bathhouse", difficulty: "medium" },
      { word: "SCHINDLERS", hint: "Holocaust rescue story", difficulty: "hard" },
      { word: "AVENGERS", hint: "Marvel superhero team-up", difficulty: "medium" },
      { word: "GODFATHER", hint: "Make him an offer he can refuse", difficulty: "medium" },
      { word: "PULPFICTION", hint: "Tarantino's non-linear crime story", difficulty: "hard" },
      { word: "NOTEBOOK", hint: "Ryan Gosling rainy kiss", difficulty: "easy" },
      { word: "BREAKINGBAD", hint: "Chemistry teacher turns criminal", difficulty: "hard" },
      { word: "GAMEOFTHRONES", hint: "Fantasy kingdom battles", difficulty: "hard" },
      { word: "FRIENDS", hint: "Six friends in New York", difficulty: "easy" },
      { word: "STRANGER", hint: "Things from the upside down", difficulty: "easy" },
      { word: "NARCOS", hint: "Colombian drug kingpin story", difficulty: "medium" },
      { word: "SHREK", hint: "Ogre in a fairytale swamp", difficulty: "easy" },
      { word: "LALALAND", hint: "Jazz musician meets actress LA", difficulty: "medium" },
      { word: "MAMAMIA", hint: "ABBA songs Swedish island", difficulty: "medium" },
      { word: "HEREDITARY", hint: "Terrifying family horror film", difficulty: "hard" },
    ],
  },
  {
    id: "activities",
    name: "Activities & Hobbies",
    emoji: "🎯",
    words: [
      { word: "DANCING", hint: "Moving to the rhythm of music", difficulty: "easy" },
      { word: "COOKING", hint: "Creating meals from scratch", difficulty: "easy" },
      { word: "HIKING", hint: "Walking trails in nature", difficulty: "easy" },
      { word: "SWIMMING", hint: "Moving through water", difficulty: "easy" },
      { word: "PAINTING", hint: "Art with brush and canvas", difficulty: "easy" },
      { word: "SINGING", hint: "Music from your voice", difficulty: "easy" },
      { word: "GAMING", hint: "Playing video or board games", difficulty: "easy" },
      { word: "YOGA", hint: "Mindful stretching practice", difficulty: "easy" },
      { word: "CYCLING", hint: "Riding on two wheels", difficulty: "easy" },
      { word: "SURFING", hint: "Riding ocean waves on a board", difficulty: "medium" },
      { word: "KARAOKE", hint: "Singing along to song lyrics", difficulty: "medium" },
      { word: "POTTERY", hint: "Clay shaped on a wheel", difficulty: "medium" },
      { word: "BAKING", hint: "Creating food in an oven", difficulty: "easy" },
      { word: "PHOTOGRAPHY", hint: "Capturing moments with a camera", difficulty: "hard" },
      { word: "MEDITATION", hint: "Mindful stillness practice", difficulty: "medium" },
      { word: "SNORKELING", hint: "Underwater breathing with a tube", difficulty: "medium" },
      { word: "SKYDIVING", hint: "Jumping from a plane for fun", difficulty: "medium" },
      { word: "KNITTING", hint: "Making fabric with needles and yarn", difficulty: "medium" },
      { word: "ORIGAMI", hint: "Japanese paper folding art", difficulty: "medium" },
      { word: "ARCHERY", hint: "Shooting arrows at a target", difficulty: "medium" },
      { word: "FENCING", hint: "Sport sword fighting", difficulty: "medium" },
      { word: "TRAMPOLINING", hint: "Bouncing high on a springy surface", difficulty: "hard" },
      { word: "CALLIGRAPHY", hint: "Beautiful decorative handwriting", difficulty: "hard" },
      { word: "STARGAZING", hint: "Watching the night sky", difficulty: "medium" },
      { word: "PARKOUR", hint: "Urban obstacle course running", difficulty: "hard" },
      { word: "WOODWORKING", hint: "Building things from timber", difficulty: "hard" },
      { word: "SCRAPBOOKING", hint: "Decorative memory album making", difficulty: "hard" },
      { word: "BEEKEEPING", hint: "Raising bees for honey", difficulty: "hard" },
      { word: "JOURNALING", hint: "Writing daily thoughts in a diary", difficulty: "medium" },
      { word: "ROLLERBLADING", hint: "Skating on inline wheels", difficulty: "hard" },
    ],
  },
  {
    id: "nature",
    name: "Nature & Animals",
    emoji: "🌿",
    words: [
      { word: "BUTTERFLY", hint: "Colorful winged insect", difficulty: "medium" },
      { word: "DOLPHIN", hint: "Intelligent ocean mammal", difficulty: "easy" },
      { word: "PENGUIN", hint: "Tuxedo-wearing Antarctic bird", difficulty: "easy" },
      { word: "FLAMINGO", hint: "Pink one-legged wading bird", difficulty: "medium" },
      { word: "SUNFLOWER", hint: "Tall yellow flower that follows the sun", difficulty: "medium" },
      { word: "RAINBOW", hint: "Arc of colors after rain", difficulty: "easy" },
      { word: "AURORA", hint: "Northern or southern lights", difficulty: "easy" },
      { word: "VOLCANO", hint: "Mountain that erupts lava", difficulty: "medium" },
      { word: "ORCHID", hint: "Exotic tropical flower", difficulty: "easy" },
      { word: "SEAHORSE", hint: "Fish that swims upright", difficulty: "medium" },
      { word: "HUMMINGBIRD", hint: "Tiny fast-flapping bird", difficulty: "hard" },
      { word: "BIOLUMINESCENCE", hint: "Ocean creatures that glow", difficulty: "hard" },
      { word: "HIBERNATION", hint: "Animal winter sleeping", difficulty: "hard" },
      { word: "MIGRATION", hint: "Animals traveling seasonally", difficulty: "medium" },
      { word: "CAMOUFLAGE", hint: "Animal color blending", difficulty: "hard" },
      { word: "PREDATOR", hint: "Animal that hunts others", difficulty: "medium" },
      { word: "ECOSYSTEM", hint: "Interconnected living system", difficulty: "hard" },
      { word: "PHOTOSYNTHESIS", hint: "Plants making food from sunlight", difficulty: "hard" },
      { word: "MANGROVE", hint: "Coastal saltwater forest tree", difficulty: "hard" },
      { word: "PLATYPUS", hint: "Egg-laying Australian mammal", difficulty: "medium" },
      { word: "CHAMELEON", hint: "Color-changing lizard", difficulty: "medium" },
      { word: "NARWHAL", hint: "Ocean unicorn whale", difficulty: "medium" },
      { word: "AXOLOTL", hint: "Smiling Mexican salamander", difficulty: "hard" },
      { word: "OCELOT", hint: "Small spotted wild cat", difficulty: "hard" },
      { word: "MANATEE", hint: "Gentle sea cow", difficulty: "medium" },
      { word: "COYOTE", hint: "Desert-dwelling wild dog", difficulty: "medium" },
      { word: "PELICAN", hint: "Bird with a big throat pouch", difficulty: "medium" },
      { word: "PRAYING MANTIS", hint: "Insect that looks like it's praying", difficulty: "hard" },
      { word: "WOLVERINE", hint: "Fierce small forest predator", difficulty: "medium" },
      { word: "ALBATROSS", hint: "Giant ocean-gliding seabird", difficulty: "hard" },
    ],
  },
  {
    id: "science",
    name: "Science & Space",
    emoji: "🚀",
    words: [
      { word: "GRAVITY", hint: "Force pulling things down", difficulty: "easy" },
      { word: "NEBULA", hint: "Colorful cloud of gas in space", difficulty: "medium" },
      { word: "QUANTUM", hint: "Physics at the smallest scale", difficulty: "hard" },
      { word: "MOLECULE", hint: "Two or more bonded atoms", difficulty: "medium" },
      { word: "SUPERNOVA", hint: "Exploding dying star", difficulty: "medium" },
      { word: "TELESCOPE", hint: "Instrument to view distant objects", difficulty: "medium" },
      { word: "ASTEROID", hint: "Rocky space object orbiting sun", difficulty: "medium" },
      { word: "CHROMOSOME", hint: "DNA-carrying structure in cells", difficulty: "hard" },
      { word: "EVOLUTION", hint: "Species change over generations", difficulty: "medium" },
      { word: "ANTIMATTER", hint: "Matter's opposite twin", difficulty: "hard" },
      { word: "BLACKHOLE", hint: "Space region nothing escapes", difficulty: "medium" },
      { word: "RELATIVITY", hint: "Einstein's famous theory", difficulty: "hard" },
      { word: "ATMOSPHERE", hint: "Layer of gas around a planet", difficulty: "medium" },
      { word: "ELEMENT", hint: "Pure chemical substance", difficulty: "easy" },
      { word: "ENTROPY", hint: "Universe tends toward disorder", difficulty: "hard" },
      { word: "PHOTON", hint: "Particle of light", difficulty: "medium" },
      { word: "NEURON", hint: "Brain nerve cell", difficulty: "medium" },
      { word: "MITOSIS", hint: "Cell division process", difficulty: "hard" },
      { word: "TECTONIC", hint: "Earth's moving crust plates", difficulty: "hard" },
      { word: "WORMHOLE", hint: "Theoretical space shortcut", difficulty: "medium" },
      { word: "PRISM", hint: "Glass that splits light into colors", difficulty: "easy" },
      { word: "CATALYST", hint: "Something that speeds reactions", difficulty: "hard" },
      { word: "EQUATION", hint: "Mathematical balance statement", difficulty: "medium" },
      { word: "FREQUENCY", hint: "Rate of wave oscillation", difficulty: "medium" },
      { word: "HYPOTHESIS", hint: "Scientific educated guess", difficulty: "hard" },
    ],
  },
  {
    id: "datenight",
    name: "Date Night",
    emoji: "🌙",
    words: [
      { word: "RESERVATION", hint: "Pre-booked restaurant table", difficulty: "hard" },
      { word: "CANDLELIT", hint: "Dinner lit by candles", difficulty: "medium" },
      { word: "BOUQUET", hint: "Arranged bunch of flowers", difficulty: "medium" },
      { word: "CHAMPAGNE", hint: "Celebratory bubbly drink", difficulty: "medium" },
      { word: "JAZZ", hint: "Smooth improvisational music", difficulty: "easy" },
      { word: "ROOFTOP", hint: "Dinner with a view from above", difficulty: "medium" },
      { word: "DESSERT", hint: "Sweet end to a meal", difficulty: "easy" },
      { word: "COMEDY", hint: "Laughing together at a show", difficulty: "easy" },
      { word: "STARGAZING", hint: "Lying back watching the night sky", difficulty: "medium" },
      { word: "SURPRISE", hint: "Unexpected special event", difficulty: "medium" },
      { word: "PLAYLIST", hint: "Curated songs for the evening", difficulty: "medium" },
      { word: "GETAWAY", hint: "Romantic weekend escape", difficulty: "medium" },
      { word: "COCKTAILS", hint: "Mixed drinks at a fancy bar", difficulty: "medium" },
      { word: "SLOW DANCE", hint: "Swaying together to music", difficulty: "medium" },
      { word: "BONFIRE", hint: "Romantic fire under the stars", difficulty: "medium" },
      { word: "STARWARS", hint: "A long time ago in a galaxy far far away", difficulty: "medium" },
      { word: "MIMOSA", hint: "Champagne and orange juice brunch drink", difficulty: "medium" },
      { word: "TERRARIUM", hint: "Miniature garden in glass", difficulty: "hard" },
      { word: "GONDOLA", hint: "Venetian romantic boat ride", difficulty: "medium" },
      { word: "SERENADE", hint: "Singing outside a window", difficulty: "medium" },
      { word: "POLAROID", hint: "Instant photo memory", difficulty: "medium" },
      { word: "FIREWORKS", hint: "Exploding sky lights", difficulty: "medium" },
      { word: "MIDNIGHT", hint: "12 AM kiss moment", difficulty: "easy" },
      { word: "HAMMOCK", hint: "Swinging between two trees", difficulty: "medium" },
      { word: "ROOFTOP", hint: "High above the city view spot", difficulty: "medium" },
    ],
  },
];

export function getRandomWord(categoryId: string): WordEntry {
  const category = CATEGORIES.find((c) => c.id === categoryId);
  if (!category) return { word: "LOVE", hint: "The best feeling", difficulty: "easy" };
  const entry = category.words[Math.floor(Math.random() * category.words.length)];
  return entry;
}

export function pickRandomWord(categoryId?: string): WordEntry {
  if (categoryId) return getRandomWord(categoryId);
  const allWords = CATEGORIES.flatMap((c) => c.words);
  return allWords[Math.floor(Math.random() * allWords.length)];
}

export function getPrefilledLetters(word: string, difficulty: "easy" | "medium" | "hard"): Set<string> {
  const unique = [...new Set(word.replace(/\s/g, "").split(""))];
  let revealCount: number;

  if (difficulty === "easy") {
    revealCount = Math.ceil(unique.length * 0.45); // reveal ~45%
  } else if (difficulty === "medium") {
    revealCount = Math.ceil(unique.length * 0.25); // reveal ~25%
  } else {
    revealCount = Math.ceil(unique.length * 0.10); // reveal ~10%
  }

  // Shuffle and pick unique letters to pre-reveal
  const shuffled = unique.sort(() => Math.random() - 0.5);
  return new Set(shuffled.slice(0, revealCount));
}
